name = "Tildagon badge simpulator"
description = "A simple simulator for Tildagon badges"
author = "Duncan Thomas <duncan.thomas@gmail.com"
packages = []

[files]
"./badge-2024-software/modules/main.py" = "main.py"
"./badge-2024-software/modules/async_queue.py" = "async_queue.py"
"./badge-2024-software/modules/perf_timer.py" = "perf_timer.py"
"./badge-2024-software/modules/app.py" = "app.py"
"./eeprom_i2c.py" = "eeprom_i2c.py"
"./badge-2024-software/modules/eeprom_partition.py" = "eeprom_partition.py"
"./tildagonos.py" = "tildagonos.py"
"./leds.py" = "leds.py"
"./sys_colors.py" = "sys_colors.py"
"./sys_display.py" = "sys_display.py"
"./badge-2024-software/sim/fakes/vfs.py" = "vfs.py"
"./badge-2024-software/modules/settings.py" = "settings.py"
"./badge-2024-software/sim/fakes/power.py" = "power.py"
"./badge-2024-software/sim/fakes/power_event.py" = "power_event.py"
"./badge-2024-software/modules/wifi.py" = "wifi.py"
"./badge-2024-software/sim/fakes/esp32.py" = "esp32.py"
"./badge-2024-software/modules/async_helpers.py" = "async_helpers.py"

"./badge-2024-software/modules/app_components/__init__.py" = "app_components/__init__.py"
"./badge-2024-software/modules/app_components/layout.py" = "app_components/layout.py"
"./badge-2024-software/modules/app_components/notification.py" = "app_components/notification.py"
"./badge-2024-software/modules/app_components/utils.py" = "app_components/utils.py"
"./badge-2024-software/modules/app_components/dialog.py" = "app_components/dialog.py"
"./badge-2024-software/modules/app_components/menu.py" = "app_components/menu.py"
"./badge-2024-software/modules/app_components/tokens.py" = "app_components/tokens.py"
"./badge-2024-software/modules/app_components/background.py" = "app_components/background.py"

"./badge-2024-software/modules/system/__init__.py" = "system/__init__.py"

"./badge-2024-software/modules/system/backgrounds/emflogo.py" = "system/backgrounds/emflogo.py"
"./badge-2024-software/modules/system/backgrounds/wigglinghexagons.py" = "system/backgrounds/wigglinghexagons.py"

"./badge-2024-software/modules/system/scheduler/__init__.py" = "system/scheduler/__init__.py"
"./badge-2024-software/modules/system/scheduler/events.py" = "system/scheduler/events.py"

"./badge-2024-software/modules/system/hexpansion/app.py" = "system/hexpansion/app.py"
"./badge-2024-software/modules/system/hexpansion/config.py" = "system/hexpansion/config.py"
"./badge-2024-software/modules/system/hexpansion/events.py" = "system/hexpansion/events.py"
"./badge-2024-software/modules/system/hexpansion/header.py" = "system/hexpansion/header.py"
"./badge-2024-software/modules/system/hexpansion/util.py" = "system/hexpansion/util.py"

"./badge-2024-software/modules/system/notification/__init__.py" = "system/notification/__init__.py"
"./badge-2024-software/modules/system/notification/events.py" = "system/notification/events.py"
"./badge-2024-software/modules/system/notification/app.py" = "system/notification/app.py"

"./badge-2024-software/modules/system/patterndisplay/__init__.py" = "system/patterndisplay/__init__.py"
"./badge-2024-software/modules/system/patterndisplay/app.py" = "system/patterndisplay/app.py"
"./badge-2024-software/modules/system/patterndisplay/events.py" = "system/patterndisplay/events.py"

"./badge-2024-software/modules/system/launcher/__init__.py" = "system/launcher/__init__.py"
"./badge-2024-software/modules/system/launcher/app.py" = "system/launcher/app.py"

"./badge-2024-software/modules/system/power/__init__.py" = "system/power/__init__.py"
"./badge-2024-software/modules/system/power/app.py" = "system/power/app.py"
"./badge-2024-software/modules/system/power/events.py" = "system/power/events.py"
"./badge-2024-software/modules/system/power/handler.py" = "system/power/handler.py"

"./badge-2024-software/modules/system/eventbus.py" = "system/eventbus.py"

"./badge-2024-software/modules/events/__init__.py" = "events/__init__.py"
"./badge-2024-software/modules/events/input.py" = "events/input.py"

"./badge-2024-software/modules/frontboards/__init__.py" = "frontboards/__init__.py"
"./badge-2024-software/modules/frontboards/twentyfour.py" = "frontboards/twentyfour.py"

"./badge-2024-software/modules/patterns/base.py" = "patterns/base.py"
"./badge-2024-software/modules/patterns/cylon.py" = "patterns/cylon.py"
"./badge-2024-software/modules/patterns/flash.py" = "patterns/flash.py"
"./badge-2024-software/modules/patterns/off.py" = "patterns/off.py"
"./badge-2024-software/modules/patterns/rainbow.py" = "patterns/rainbow.py"

"./badge-2024-software/modules/firmware_apps/__init__.py" = "firmware_apps/__init__.py"
"./badge-2024-software/modules/firmware_apps/intro_app.py" = "firmware_apps/intro_app.py"
"./badge-2024-software/modules/firmware_apps/poweroff.py" = "firmware_apps/poweroff.py"
"./badge-2024-software/modules/firmware_apps/text_demo.py" = "firmware_apps/text_demo.py"
"./badge-2024-software/modules/firmware_apps/app_store.py" = "firmware_apps/app_store.py"
"./badge-2024-software/modules/firmware_apps/menu_demo.py" = "firmware_apps/menu_demo.py"
"./badge-2024-software/modules/firmware_apps/settings_app.py" = "firmware_apps/settings_app.py"
"./badge-2024-software/modules/firmware_apps/tick_app.py" = "firmware_apps/tick_app.py"
"./badge-2024-software/modules/firmware_apps/basic_app.py" = "firmware_apps/basic_app.py"
"./badge-2024-software/modules/firmware_apps/patterninhibit.py" = "firmware_apps/patterninhibit.py"
"./badge-2024-software/modules/firmware_apps/sponsors.py" = "firmware_apps/sponsors.py"
"./badge-2024-software/modules/firmware_apps/hexpansion_test.py" = "firmware_apps/hexpansion_test.py"
"./badge-2024-software/modules/firmware_apps/pingpong_app.py" = "firmware_apps/pingpong_app.py"
"./badge-2024-software/modules/firmware_apps/test_app.py" = "firmware_apps/test_app.py"
